### ISSUE TITLE
Problem running tests

### ISSUE THREAD

**Issue by cartuchogl** [mikeseven/node-webgl#11]
Hello,

I clone the lastest version and I try to run test/glversion.js with that result

```
$ node test/glversion.js 

/Users/cartucho/Repositories/webgl/node-webgl/lib/platform_glfw.js:75
            GLFW.OpenWindowHint(GLFW.WINDOW_NO_RESIZE, 0);
                 ^
TypeError: Object #<Object> has no method 'OpenWindowHint'
    at Object.platform.createWindow (/Users/cartucho/Repositories/webgl/node-webgl/lib/platform_glfw.js:75:18)
    at Object.platform.createElement (/Users/cartucho/Repositories/webgl/node-webgl/lib/platform_glfw.js:55:22)
    at Object.<anonymous> (/Users/cartucho/Repositories/webgl/node-webgl/test/glversion.js:5:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

I try to change the call to OpenWindowHint to WindowHint and then fail with

```
/Users/cartucho/Repositories/webgl/node-webgl/lib/platform_glfw.js:83
            if (!GLFW.OpenWindow(width, height,
                      ^
TypeError: Object #<Object> has no method 'OpenWindow'
    at Object.platform.createWindow (/Users/cartucho/Repositories/webgl/node-webgl/lib/platform_glfw.js:83:23)
    at Object.platform.createElement (/Users/cartucho/Repositories/webgl/node-webgl/lib/platform_glfw.js:55:22)
....
```

After Modify OpenWindow call to CreateWindow and minor dirty changes like:

```
var kk = GLFW.CreateWindow(width, height, "test");

// make sure GLEW is initialized
WebGL.Init();

//GLFW.SwapBuffers();
GLFW.SwapInterval(0); // Disable VSync (we want to get as high FPS as possible!)

for (var l = 0, ln = resizeListeners.length; l < ln; ++l)
    GLFW.events.addListener('resize', resizeListeners[l]);

var size = GLFW.GetWindowSize(kk);
```

And now this test runs...
But when try another tests like lesson02.js, it open a 800x800 black window that only can force close to exit.

This tests are over a MacOSX 10.8.5 with a NVIDIA GeForce GTX 660M

Any idea?

Thanks for your support.

**Comment by geloescht** [comment]
Could maybe be related to this bug on intel GPUs: https://bugs.freedesktop.org/show_bug.cgi?id=84252

I captured an (incomplete due to missing debug symbols) backtrace from gdb:
#0  0x00007ffff61563dd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fffee1a7b72 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fffee1a8f91 in xcb_wait_for_special_event ()
   from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007ffff51aae44 in ?? () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#4  0x00007ffff51ab52d in ?? () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#5  0x00007ffff51ac122 in ?? () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#6  0x00007fffeb0df497 in intel_update_image_buffers (
    drawable=<optimized out>, brw=<optimized out>)
    at ../../../../../../../src/mesa/drivers/dri/i965/brw_context.c:1453
#7  intel_update_renderbuffers (context=0x7fffffffd190, 
    context@entry=0x810460, drawable=0x80ef60)
    at ../../../../../../../src/mesa/drivers/dri/i965/brw_context.c:1145
#8  0x00007fffeb0df7c5 in intel_prepare_render (brw=brw@entry=0x907508)
    at ../../../../../../../src/mesa/drivers/dri/i965/brw_context.c:1166
#9  0x00007fffeb0d41ed in brw_clear (ctx=0x907508, mask=18)
    at ../../../../../../../src/mesa/drivers/dri/i965/brw_clear.c:234
#10 0x00007ffff593d443 in webgl::Clear(v8::Arguments const&) ()
   from /home/lukas/Programmieren/vvvv_js/node_modules/node-webgl/build/Release/webgl.node
#11 0x00007ffff743f313 in ?? () from /usr/lib/libv8.so.3.14.5
#12 0x00002199c8f06362 in ?? ()
#13 0x00002199c8f062c1 in ?? ()

hschougaard, could you please run an example in gdb, interrupt the process when it hangs and capture a backtrace in order to confirm we are having the same issue?
